l_trad_chinese:
	SETTING_VALUE_NONE:0 "$VALUE$"
	SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
	SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
	SETTING_VALUE_SECONDS:0 "$VALUE$秒"
	SETTING_VALUE_MINUTES:0 "$VALUE$分鐘"
	SETTING_RENDERER:0 "渲染器"
	SETTING_RENDERER_TOOLTIP:0 "決定使用哪種渲染器。"
	SETTING_VSYNC:0 "垂直同步"
	SETTING_VSYNC_TOOLTIP:0 "#T $SETTING_VSYNC$\n#!使遊戲的幀率與顯示器的刷新率同步。\n\n關閉此選項可能會提升性能。"
	SETTING_PORTRAIT_MULTI_SAMPLING:0 "肖像對重採樣"
	SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!使用多重採樣Alpha-To-Coverage（A2C）使得頭髮絲的混合更加柔順。\n\n降低設置可能會提高性能。"
	SETTING_MULTI_SAMPLING:0 "抗鋸齒（MSAA）"
	SETTING_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_MULTI_SAMPLING$\n#!採用多重採樣抗鋸齒（MSAA）能夠使圖像邊緣更加平滑。\n\n降低設置可能會提高性能。"
	SETTING_ANTI_ALIASING:0 "抗鋸齒"
	SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!採用抗鋸齒能夠使得圖像邊緣變的更加平滑。\n\n推薦使用FXAA"
	OPTION_ANTI_ALIASING_DISABLED:0 "已禁用"
	OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
	SETTING_ANISOTROPIC_FILTERING:0 "材質過濾"
	SETTING_ANISOTROPIC_FILTERING_TOOLTIP:0 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!採用各向異性過濾能夠使貼圖表面表現更佳。\n\n降低設置可能會提高性能。"
	SETTING_FULLSCREEN_RESOLUTION:0 "解析度"
	SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:0 "#T $SETTING_FULLSCREEN_RESOLUTION$#!\n設定遊戲的圖像質量。\n\n降低解析度會提高性能。\n\n#X使用不受支持的縱橫比的分辨率可能會導致界面超出螢幕#!"
	SETTING_WINDOWED_RESOLUTION:0 "窗口化解析度"
	SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "#T$SETTING_WINDOWED_RESOLUTION$#!\n設置遊戲處於窗口模式時的遊戲分辨率。\n\n格式必須為#b 數值#!x#b 數值#!。\n\n#X縱橫比不受支持的遊戲分辨率可能會導致界面出現在螢幕之外#!"
	SETTING_RENDER_SCALE:0 "渲染比例"
	SETTING_RENDER_SCALE_TOOLTIP:0 "#T$SETTING_RENDER_SCALE$#!\n除開用戶界面，遊戲的渲染分辨率相對於主解析度的比例。\n\n較低的設置可能會提高性能並降低整體的精確度，超過100%則會提高精確度但降低性能。"
	SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
	SETTING_DISPLAY:0 "顯示器"
	SETTING_DISPLAY_TOOLTIP:0 "#T $SETTING_DISPLAY$\n#!如果你的電腦有多個顯示器，選擇遊戲要使用哪一個。"
	SETTING_GRAPHICS_DEVICE:0 "顯卡"
	SETTING_GRAPHICS_DEVICE_TOOLTIP:0 "#T $SETTING_GRAPHICS_DEVICE$\n#!選擇遊戲使用的顯卡。\n\n使用集成顯卡或者軟體渲染器會降低性能。"
	SETTING_SHADOW_MAP_RESOLUTION:0 "陰影質量"
	SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:0 "#T$SETTING_SHADOW_MAP_RESOLUTION$\n#!開啟陰影時，決定陰影貼圖渲染的分辨率。\n\n降低設置可能會提高性能。"
	SETTING_DISPLAY_MODE:0 "顯示模式"
	SETTING_DISPLAY_MODE_TOOLTIP:0 "#T $SETTING_DISPLAY_MODE$\n#!選擇你需要的顯示模式"
	SETTING_BLOOM:0 "泛光"
	SETTING_MESH_LOD_BIAS:0 "網格多層次細節質量"
	SETTING_MESH_LOD_FADE:0 "網格多層次細節漸變"
	SETTING_TERRAIN_SMOOTHING:0 "地形平滑"
	OPTION_FULLSCREEN:0 "全屏"
	OPTION_FULLSCREEN_TOOLTIP:0 "#T$OPTION_FULLSCREEN$\n#!以全屏模式顯示遊戲，分辨率設置將會更改整體的圖像清晰度。"
	OPTION_WINDOWED:0 "窗口"
	OPTION_WINDOWED_TOOLTIP:0 "#T$OPTION_WINDOWED$\n#!以窗口模式顯示遊戲，分辨率設置將會更改窗口的大小。"
	OPTION_DISABLED:0 "已禁用"
	OPTION_OFF:0 "關閉"
	OPTION_LOW:0 "低"
	OPTION_MEDIUM:0 "中"
	OPTION_HIGH:0 "高"
	OPTION_ULTRA:0 "極致"
	OPTION_CUSTOM:0 "自定義"
	OPTION_DEFAULT:0 "默認"
	SETTINGS_CATEGORY_UI:0 "界面"
	SETTINGS_CATEGORY_GAME:0 "遊戲"
	SETTING_TEXTURE_QUALITY:0 "材質質量"
	SETTING_TEXTURE_QUALITY_TOOLTIP:0 "#T$SETTING_TEXTURE_QUALITY$#!\n控制已加載材質的分辨率。\n\n降低設置可能會提高性能。"
	SETTING_QUALITY:0 "質量預設"
	SETTING_SFX:0 "特效"
	SETTING_UI:0 "界面"
	SETTING_QUALITY_TOOLTIP:0 "#T $SETTING_QUALITY$\n#!從以下選擇一個預設的高級圖像選項。\n\n較低的預設能提升性能。"
	SETTING_BLOOM_TOOLTIP:0 "#T $SETTING_BLOOM$\n#!啟用「光暈」效果，圖像中的高光部分將會溢出到圖像的其他部分上。\n\n將其關閉可能會提高性能。"
	SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!啟用景深以模擬相機鏡頭，模糊圖像的失焦點。\n\n關閉此項可能會提升性能。"
	SETTING_MAP_SSAO_TOOLTIP:0 "#T$SETTING_MAP_SSAO$\n#!決定屏幕空間的環境閉鎖是否應用到地圖。\n\n關閉可能提升性能"
	SETTING_REFRACTION_TOOLTIP:0 "決定水面上是否出現折射。"
	SETTING_REFRACTION_QUALITY_TOOLTIP:0 "#T $SETTING_REFRACTION_QUALITY$#!\n如果啟用水面折射，控制水面折射的質量。\n\n降低設置可能會提高性能。"
	SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "#T $SETTING_MAPOBJECT_QUALITY$#!\n決定地圖物件（如建築物）的最高質量等級。\n\n降低設置可能會提高性能。"
	SETTING_MESH_LOD_BIAS_TOOLTIP:0 "#T $SETTING_MESH_LOD_BIAS$#!\n決定地圖物件（如單位模型）的多層次細節（細節級別）的質量。\n\n降低設置可能會提高性能。"
	SETTING_MESH_LOD_FADE_TOOLTIP:0 "#T $SETTING_MESH_LOD_FADE$\n#!啟用後，三維模型會在視角距離更改時，在不同等級的細節度（LOD）之間平滑轉變。\n\n關閉此項可能會提升性能。"
	SETTING_PROVINCE_NAMES_TOOLTIP:0 "決定城市和省份名字如何顯示。"
	SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "決定地圖上某個國家的邊界內是否包含無法通行的地形。"
	SETTING_LANGUAGE_TOOLTIP:0 "#T $SETTING_LANGUAGE$#!\n決定用戶界面所用的語言。"
	SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "你的Paradox賬號電子郵箱"
	SETTING_FRAMERATE_CAP:0 "幀數上限"
	SETTING_FRAMERATE_CAP_TOOLTIP:0 "#T $SETTING_FRAMERATE_CAP$#!\n遊戲最大幀數。\n\n降低該設置可以減少能耗。"
	OPTION_CAP_30:0 "30"
	OPTION_CAP_60:0 "60"
	OPTION_CAP_90:0 "90"
	OPTION_CAP_120:0 "120"
	OPTION_CAP_144:0 "144"
	OPTION_CAP_165:0 "165"
	SETTING_TEXTURE_STREAMING:0 "紋理流"
	SETTING_TEXTURE_STREAMING_TOOLTIP:0 "#T $SETTING_TEXTURE_STREAMING$#!理將按需加載\n低 GPU 內存使用量，但增加一定的 CPU 時間開銷。可能會提高具有少量內存的 GPU 的性能。"
	SETTING_TEXTURE_STREAMING_CACHE:0 "紋理流緩存大小"
	SETTING_VALUE_MB:0 "$VALUE$ MB"
	SETTING_ANIMATION_SPEED:0 "動畫速度"
	SETTING_GUI_SCALING:0 "圖形用戶界面縮放比例"
	SETTING_GUI_SCALING_TOOLTIP:0 "#T $SETTING_GUI_SCALING$\n#!設置整個用戶界面的縮放比例。對於高解析度螢幕有用。\n\n#X設置過高可能會使得界面無法適配進入屏幕！#!"
	SETTING_SCREEN_EDGE_SCROLL_MODE:0 "滑鼠平移"
	SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "自由"
	SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "八向移動"
	SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "已禁用"
	SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T$SETTING_SCREEN_EDGE_SCROLL_MODE$#!\n當用鼠標平移時視角如何變化。"
	SETTING_SCROLL_SPEED:0 "平移速度"
	SETTING_SCROLL_SPEED_TOOLTIP:0 "#T$SETTING_SCROLL_SPEED$#!\n當使用鍵盤或者鼠標時，設置地圖平移有多快。"
	SETTING_CAMERA_ROTATION_SPEED:0 "視角旋轉速度"
	SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\n視角旋轉的速度。"
	SETTING_ZOOM_SPEED:0 "縮放速度"
	SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\n視角縮放的速度。"
	SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "縮放行為"
	SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "相對光標"
	SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "朝光標放大"
	SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "忽略光標"
	SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\n當縮放時，視角相對光標的運動行為。"
	SETTING_INPUT_DEVICE:0 "輸入設備"
	SETTING_EDITOR:0 "編輯器"
	SETTING_EDITOR_POSTFIX:0 "編輯器後綴"
	SETTING_EDITOR_OPEN_FILE_FORMAT:0 "編輯器開啟指令"
	SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "查看日誌指令"
	SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "代碼編輯器開啟指令"
	SETTING_GRACEFUL_EXIT:0 "平穩退出"
	SETTING_LANGUAGE:0 "語言"
	MOUSE_AND_KEYBOARD:0 "滑鼠和鍵盤"
	GAMEPAD:0 "手柄"
	SETTING_MULTISAMPLING_DISABLED:0 "禁用"
	SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "禁用"
	SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "禁用"
	SETTING_CAMERA_TILT:0 "視角傾斜"
	SETTING_CAMERA_STRATEGY:0 "視角類型"
	SETTING_CENTERED_ZOOM_IN:0 "中心放大"
	SETTING_CAMERA_SPEED:0 "視角速度"
	CAMERA_TABLETOP:0 "桌面頂部"
	CAMERA_FPS:0 "第一人稱"
	CAMERA_WASD:0 "WASD風格"
	SETTING_Music:0 "音樂"
	SETTING_Ambient:0 "周邊環境"
	SETTING_Effects:0 "效果"
	SETTING_Master:0 "主要"
	SETTING_Master_TOOLTIP:0 "#T 主音量#!\n設定遊戲內所有聲音的音量。"
	SETTING_Music_TOOLTIP:0 "#T 音樂音量#!\n設定音樂的音量。"
	SETTING_Ambient_TOOLTIP:0 "#T 環境音量\n#!設置周邊環境音效的音量。"
	SETTING_SFX_TOOLTIP:0 "#T 特效音量\n#!設置聲音效果的音量，如戰鬥。"
	SETTING_UI_TOOLTIP:0 "#T 界面音量\n#!設置用戶界面的音量。"
	SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Debug日誌等級"
	SETTING_AUDIO_DEVICE_PROFILE:0 "音頻配置"
	SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#! 選擇適合您設置的音頻配置。"
	SETTING_AUDIO_OPTION_SPEAKERS:0 "揚聲器"
	SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#! $SETTING_AUDIO_OPTION_SPEAKERS$的默認混音。"
	SETTING_AUDIO_OPTION_HEADPHONES:0 "耳機"
	SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#! 適合$SETTING_AUDIO_OPTION_HEADPHONES$的混音。"
	SETTING_AUDIO_OPTION_TV:0 "TV"
	SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$#!\n$SETTING_AUDIO_OPTION_TV$和顯示器揚聲器混音。"
	SETTING_AUDIO_OPTION_NIGHTMODE:0 "夜晚模式"
	SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$#!\n柔和夜間播放的聲音，調低較高的音高，壓縮動態範圍。"
	SETTING_AUTOSAVE:0 "自動保存間隔"
	SETTING_AUTOSAVE_TOOLTIP:0 "#T $SETTING_AUTOSAVE$\n#!設定遊戲自動保存的頻率。"
	SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "決定是否將自動存檔保存到雲端。"
	SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "決定視角是否始終朝北。"
	NO_AUTOSAVE:0 "禁用自動存檔"
	SETTINGS_FILE_TRANSFER_SPEED:0 "文件傳輸速度"
	SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T 文件傳輸速度\n#!設置多人遊戲大廳裡存檔文件傳輸時的最大速度。\n\n降低設置可能會改善加入多人遊戲時的網路穩定程度，但對於多人遊戲的載入時間會產生負面效果。"
	SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "地圖編輯器自動保存（分鐘）"
	SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "地圖編輯器自動保存間隔（分鐘）"
	SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "節點編輯器拖動平移模式"
	SETTINGS_CATEGORY_ACCESSIBILITY:0 "可訪問性"
	SETTING_COLOR_BLIND_MODE:0 "色盲模式"
	SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!將遊戲文本使用的顏色更改為各類色盲人群更容易區分的一組顏色。"
	SETTING_MOUSE_PANNING:0 "滑鼠捲動"
	SETTING_MOUSE_PANNING_TOOLTIP:0 "#T$SETTING_MOUSE_PANNING$\n#!設置大地圖是否可以通過鼠標移動到螢幕或窗口邊緣滾動。"
