l_trad_chinese:
	SETTING_VALUE_WARNING:0 "$VALUE|0X$"
	SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
	RECOMMENDED_GUI_SCALE_TOO_HIGH:0 "#X放大超過$VALUE|%0$可能會導致界面超出屏幕範圍#!"
	RECOMMENDED_GUI_SCALE:0 "放大超過$VALUE|%0$可能會導致界面超出螢幕範圍"
