l_trad_chinese:
	SETTING_DEBUG_SAVES:0 "調試存檔數量"
	SETTING_TUTORIAL:0 "教程"
	SETTING_DISABLED_HINTS:0 "關閉提示"
	SETTING_TOOLTIP_DELAY:0 "彈框提示延遲"
	SETTING_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_TOOLTIP_DELAY$#!\n設置彈框提示出現之前的延時。"
	SETTING_TOOLTIP_UNLOCK_TIME:0 "解鎖的延遲"
	SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n設置彈框提示解鎖之前的延時。"
	SETTING_TOOLTIP_LOCK_TIME:0 "鎖定的延遲"
	SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n設置彈框提示鎖定之前的延時。"
	SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "已開啟時的鎖定延時"
	SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n設置已打開另一彈框提示時，彈框提示鎖定之前的延時。"
	SETTING_Sound_Effects:0 "所有音效"
	SETTING_Sound_Effects_TOOLTIP:0 "#T 音效音量\n#!設定所有音效的音量。"
	SETTING_Ambience:0 "環境音效"
	SETTING_Ambience_TOOLTIP:0 "#T 環境音效音量\n#!設定環境音效音量。"
	SETTING_TOOLTIP_MODE:0 "彈框提示模式"
	SETTING_TOOLTIP_MODE_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE$#!\n設置彈框提示「固定」的方式，允許彈框提示中的彈框提示。"
	SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "滑鼠趨勢"
	SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\n彈框提示自動鎖定直到光標移開。"
	SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "動作鎖定"
	SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T$SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n按下#V鼠標中鍵#!以鎖定和解鎖彈框提示。"
	SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "定時鎖定"
	SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\n如果光標短時間內不移動，則彈框提示鎖定。#weak （默認設置。）#!"
	SETTINGS_CATEGORY_INTERFACE_MISC:0 "雜項"
	SETTINGS_CATEGORY_TOOLTIPS:0 "彈框提示"
	SETTINGS_CATEGORY_SFX:0 "特殊音效"
	SETTINGS_CATEGORY_AUDIO_GENERAL:0 "通用"
	SETTINGS_CATEGORY_MAP_CONTROLS:0 "地圖控制"
	SETTINGS_CATEGORY_SAVE_GAMES:0 "保存遊戲"
	SETTINGS_CATEGORY_LANGUAGE:0 "語言"
	SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "高級——通用"
	SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "高級——地圖"
	SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "高級——角色"
	SETTINGS_CATEGORY_GAME_PORTRAITS:0 "肖像"
	SETTINGS_CATEGORY_GAME_FLAVOR:0 "風味"
	SETTINGS_CATEGORY_MULTIPLAYER:0 "多人遊戲"
	SETTINGS_CATEGORY_MAP:0 "地圖"
	SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "顯示外傷與體表症狀"
	SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n設置是否在角色肖像上顯示外傷與體表症狀。"
	SETTING_SHOW_NUDITY:0 "顯示裸體"
	SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\n設定角色是否會顯示裸體。"
	SETTINGS_CATEGORY_GAME_DLC_MODS:0 "可下載內容"
	SETTING_SHOW_CONTENT_SOURCE:0 "顯示事件DLC"
	SETTING_SHOW_CONTENT_SOURCE_TOOLTIP:0 "#T $SETTING_SHOW_CONTENT_SOURCE$#!\n設定事件是否顯示其所屬的DLC。"
	SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "朝廷閒置時鏡頭移動"
	SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\n決定朝廷中的鏡頭在閒置時會不會慢慢在你的宮廷裡轉動。\n\n如果動態角色是關閉的，該設置無效果。"
	SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "朝廷平滑轉換"
	SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\n決定朝廷中的鏡頭移動到新位置時是否平滑。\n\n如果動態角色是關閉的，該設置無效果。"
	NEVER:0 "從不"
	MONTHLY:0 "每月"
	HALFYEAR:0 "每六個月"
	YEARLY:0 "每年"
	FIVE_YEAR:0 "每五年"
	SETTINGS_CATEGORY_TUTORIAL:0 "教程"
	SETTING_REACTIVE_TUTORIAL:0 "顯示響應式建議"
	SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\n設置是否在遊戲過程中針對性地顯示教程。對《十字軍之王3》的新玩家非常有用。"
	SETTING_SHOW_SUGGESTIONS:0 "顯示建議"
	SETTING_SHOW_SUGGESTIONS_TOOLTIP:0 "#T $SETTING_SHOW_SUGGESTIONS$#!\n設置遊戲是否進行常規操作提示。對《十字軍之王3》的新玩家非常有用。"
	RESET_REACTIVE_ADVICE:0 "重置響應式建議"
	RESET_REACTIVE_ADVICE_TOOLTIP:0 "#T 重置響應式建議#!\n之前看過的響應式建議將會再次顯示一次。"
	RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "重置響應式建議"
	RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "你確定要重置響應式建議嗎？"
	SETTING_ADVANCED_SHADERS:0 "高級著色器效果"
	SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T 高級著色器效果\n#!此選項啟用高級著色器效果。\n\n關閉可以提升性能，但會犧牲某些特效（例如地形和水域）"
	SETTING_WINTER_PARTICLE_EFFECTS:0 "冬季粒子效果"
	SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\n設置當冬天來臨時，地圖上的某些地區是否顯示粒子效果。\n\n關閉此選項能夠提升性能"
	SETTING_RESET_CAMERA_ROTATION:0 "重置視角旋轉"
	SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\n確定視角在用戶旋轉後是否應自動重置回默認位置。"
	SETTING_TILT_CAMERA_ON_ZOOM_OUT:0 "拉遠鏡頭時傾斜視角"
	SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP:0 "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\n確定拉遠鏡頭時視角是否應向默認方向傾斜。"
	SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "宮廷場景背景角色"
	SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\n決定朝廷的3D場景是否要顯示較不重要的背景角色。"
	SETTING_MAP_HIGHLIGHT:0 "光標處地圖高亮"
	SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\n確定光標所處地圖位置的高亮強度"
	BASED_ON_ZOOM_LEVEL:0 "動態"
	ALWAYS_HIDE:0 "總是隱藏"
	ALWAYS_SHOW:0 "總是顯示"
	SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "海岸線"
	SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n此選項控制領地海岸線何時顯示。\n$BASED_ON_ZOOM_LEVEL$下，海岸線將在細節縮放級別時隱藏。\n\n選擇$ALWAYS_SHOW$或$ALWAYS_HIDE$可能提升性能，但會讓領地海岸線無法自動隱藏。"
	SETTINGS_DISCARD_CHANGES:0 "放棄變更"
	SETTING_HUD_SKIN:0 "HUD皮膚"
	hud_skin_auto:0 "動態"
	default:0 "默認"
	iberian:0 "伊比利亞"
	Norse:0 "諾斯"
	iranian:0 "$e_persia_adj$"
	SETTING_HUD_SKIN_TOOLTIP:0 "#T $SETTING_HUD_SKIN$#!\n設置HUD界面——在遊戲主屏顯示的2D UI的視覺主題。\n\n如果選中$hud_skin_auto$，HUD會根據玩家的文化、信仰和領地首都而變動。"
	SETTING_RICH_PRESENCE:0 "豐富資訊"
	SETTING_RICH_PRESENCE_TOOLTIP:0 "#T$SETTING_RICH_PRESENCE$#!\n若平台支持，向好友顯示你當前的遊戲信息。"
	SETTING_USE_DYNASTY_NAMED_REALMS:0 "宗族命名領地"
	SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\n某些文化會以其宗族名命名主頭銜（例如：阿拔斯）。"
	map_table_style_auto:0 "動態"
	map_table_style_western:0 "默認"
	map_table_style_ce1:0 "瘟疫"
	SETTING_MAP_TABLE_STYLE:0 "地圖桌樣式"
	SETTING_MAP_TABLE_STYLE_TOOLTIP:0 "#T $SETTING_MAP_TABLE_STYLE$#!\n設置地圖桌——拉遠時顯示的地圖和三維環境——的視覺風格。\n\n如果選擇了$map_table_style_auto$，地圖桌樣式會根據當前玩家和角色進行選擇。"
	SETTINGS_CATEGORY_STYLING:0 "界面樣式"
	SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS:0 "疾病圖像"
	SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP:0 "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\n設置疾病效果是否在地圖上顯示"
	SETTING_SHOW_LEGEND_MAP_GRAPHICS:0 "傳奇圖像"
	SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP:0 "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\n設置傳奇效果是否在地圖上顯示"
	SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED:0 "羊皮紙地圖佈光"
	SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED_TOOLTIP:0 "#T $SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED$#!\n設置羊皮紙地圖是否接受地圖桌的光亮與陰影。（禁用該項會獲得經典的羊皮紙地圖著色）"
