l_trad_chinese:
	SETTINGS_PAGE_GRAPHICS:0 "圖像"
	SETTINGS_PAGE_GAME:0 "遊戲"
	SETTINGS_PAGE_SYSTEM:0 "系統"
	SETTINGS_PAGE_CONTROLS:0 "控制"
	SETTINGS_PAGE_EDITOR:0 "編輯器"
	SETTINGS_PAGE_INTERFACE:0 "界面"
	SETTINGS_PAGE_AUDIO:0 "聲音"
	SETTINGS_CATEGORY_SCREEN:0 "螢幕"
	SETTINGS_CATEGORY_QUALITY:0 "質量"
	OPTION_EASY:0 "簡單"
	OPTION_NORMAL:0 "正常"
	OPTION_HARD:0 "困難"
	OPTION_NEVER:0 "永不"
	OPTION_MONTHLY:0 "每月"
	OPTION_HALFYEAR:0 "每半年"
	OPTION_YEARLY:0 "每年"
	OPTION_FIVE_YEAR:0 "每五年"
	OPTION_NO_AUTOSAVE:0 "禁用自動存檔"
	SETTINGS_CATEGORY_ACCOUNT:0 "賬號"
	SETTINGS_CATEGORY_SYSTEM:0 "系統"
	SETTINGS_CATEGORY_CONTROLS:0 "控制"
	SETTINGS_CATEGORY_CAMERA:0 "視角"
	SETTINGS_CATEGORY_AUDIO:0 "聲音"
	SETTINGS_CATEGORY_GUI:0 "圖形用戶界面"
	SETTINGS_CATEGORY_INPUT_BINDINGS:0 "輸入綁定"
	DISCARD:0 "放棄"
	APPLY:0 "應用"
	SAVE_AND_CLOSE:0 "確定"
	SETTINGS:0 "設置"
	REQUIRES_RESTART:0 "需要重啟遊戲"
	REQUIRE_RESTART_DESCRIPTION:0 "部分設置需要重啟遊戲後才能生效。"
	SETTINGS_INPUT_REMAP_INPUT:0 "重映射輸入"
	SETTINGS_INPUT_CONFIRM:0 "確認"
	SETTINGS_INPUT_CANCEL:0 "取消"
	SETTINGS_INPUT_CLEAR:0 "清除"
	SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "保存檔案"
	SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "加載檔案"
	SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "重置為默認值"
	SETTINGS_INPUT_BINDING_TEXT:0 "請為「$INPUT_ACTION$」行動選擇一個輸入綁定：\n\n$INPUT_NAME$"
	SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "警告：這個輸入綁定對於「$INPUT_ACTION$」已存在！\n按「$SETTINGS_INPUT_CONFIRM$」會清除舊綁定"
	RESTORE:0 "重置"
